// Generated by Khrysalis TypeScript converter - this file will be overwritten.
// File: uuids.kt
// Package: com.lightningkite.butterfly.bluetooth

//! Declares com.lightningkite.butterfly.bluetooth.notificationDescriptorUuid
export const _notificationDescriptorUuid: string = "00002902-0000-1000-8000-00805f9b34fb";
export function getNotificationDescriptorUuid(): string { return _notificationDescriptorUuid; }

